import { stat,readFile } from "node:fs/promises";
import { resolve } from "node:path";
export const MATURITY_STATES=Object.freeze({artifact:Object.freeze(["experimental","candidate","stable"]),contract_api:Object.freeze(["experimental","candidate","stable"]),runtime_adapter:Object.freeze(["experimental","candidate","stable"]),behavioral_evidence:Object.freeze(["unproven","evaluated-case","repeated"]),real_world_workflow:Object.freeze(["unproven","collecting","demonstrated"]),provider_lifecycle:Object.freeze(["not-run","partial","validated"])});
const nonEmpty=(v)=>typeof v==="string"&&v.trim().length>0;async function exists(root,path){try{await stat(resolve(root,path));return true;}catch{return false;}}
export async function validateMaturityModel(model,{root=resolve(import.meta.dirname,"../.."),evidenceValidation,browserResults,memoryResults,realTaskStatus}={}){
 const errors=[],dims=model?.dimensions||{};
 if(model?.schema!==1)errors.push("maturity schema must be 1");if(!nonEmpty(model?.candidate)||!nonEmpty(model?.baseline_release))errors.push("candidate and baseline_release required");
 for(const [dimension,states] of Object.entries(MATURITY_STATES)){const entry=dims[dimension];if(!entry){errors.push("missing maturity dimension "+dimension);continue;}if(!states.includes(entry.state))errors.push(dimension+": invalid state "+String(entry.state));if(!Array.isArray(entry.basis)||!entry.basis.length)errors.push(dimension+": basis required");if(!nonEmpty(entry.rationale))errors.push(dimension+": rationale required");for(const path of entry.basis||[])if(!await exists(root,path))errors.push(dimension+": basis path missing: "+path);}
 if(Object.keys(dims).some((key)=>!Object.hasOwn(MATURITY_STATES,key)))errors.push("unknown maturity dimension");
 if(model?.rules?.no_cross_dimension_promotion!==true)errors.push("no_cross_dimension_promotion must be true");
 if(model?.rules?.stable_artifact_does_not_imply_stable_behavior!==true)errors.push("stable artifact independence rule required");
 if(!nonEmpty(model?.historical_truth?.deferred_evidence_source))errors.push("historical v0.4 deferred evidence source required");else if(!await exists(root,model.historical_truth.deferred_evidence_source))errors.push("historical deferred evidence source missing");
 const supportedBehavioral=Object.entries(evidenceValidation?.claims||{}).filter(([,v])=>v.computed_status==="SUPPORTED"&&(v.qualifying_classes||[]).some((cls)=>["BLACK_BOX_EXTERNAL_BEHAVIOR","CROSS_IMPLEMENTATION","LIVE_RUNTIME_EVIDENCE","REAL_WORLD_EVIDENCE"].includes(cls)));
 if(dims.behavioral_evidence?.state==="evaluated-case"&&!supportedBehavioral.length)errors.push("behavioral_evidence evaluated-case requires at least one externally observed/cross-implementation supported case");
 if(dims.behavioral_evidence?.state==="repeated"){const ids=new Set();for(const [,v] of supportedBehavioral)for(const id of v.qualifying_evidence||[])ids.add(id);if(ids.size<2)errors.push("behavioral_evidence repeated requires multiple qualifying evidence records");}
 const realClaim=evidenceValidation?.claims?.["real-world-workflow-demonstrated"];
 if(dims.real_world_workflow?.state==="collecting"&&realClaim?.computed_status!=="COLLECTING")errors.push("real_world_workflow collecting must match canonical evidence claim");
 if(dims.real_world_workflow?.state==="demonstrated"&&realClaim?.computed_status!=="SUPPORTED")errors.push("real_world_workflow demonstrated requires supported real-world claim");
 if(dims.real_world_workflow?.state==="collecting"&&realTaskStatus?.status!=="COLLECTING")errors.push("real-world maturity drift: canonical real-task status is "+String(realTaskStatus?.status));
 const providers=[...(browserResults?.providers||[]),...(memoryResults?.providers||[])],completed=providers.filter((x)=>x.status==="COMPLETED"&&x.summary?.acceptance_passed===true).length,open=providers.filter((x)=>x.status!=="COMPLETED"||x.summary?.acceptance_passed!==true).length;
 if(dims.provider_lifecycle?.state==="not-run"&&completed!==0)errors.push("provider_lifecycle not-run conflicts with completed provider evidence");
 if(dims.provider_lifecycle?.state==="partial"&&!(completed>0&&open>0))errors.push("provider_lifecycle partial requires both completed and open provider evidence");
 if(dims.provider_lifecycle?.state==="validated"&&!(providers.length>0&&open===0))errors.push("provider_lifecycle validated requires all inventoried providers completed and accepted");
 return Object.freeze({ok:!errors.length,errors:Object.freeze(errors),candidate:model?.candidate||"UNKNOWN",dimensions:Object.freeze(Object.fromEntries(Object.keys(MATURITY_STATES).map((k)=>[k,dims[k]?.state||"UNKNOWN"]))),behavioral_supported_cases:supportedBehavioral.length,provider_summary:Object.freeze({total:providers.length,completed_accepted:completed,open}),real_task_status:realTaskStatus?.status||"UNKNOWN"});
}
export function buildMaturitySnapshot({model,validation}){if(!validation?.ok)throw new Error("cannot snapshot invalid maturity model");return Object.freeze({schema:1,candidate:model.candidate,baseline_release:model.baseline_release,dimensions:validation.dimensions,truth_boundary:"artifact maturity != contract maturity != adapter maturity != behavioral evidence != real-world demonstration != provider lifecycle",historical_v0_4_truth_preserved:true});}
export async function readMaturityInputs({root=resolve(import.meta.dirname,"../..")}={}){const readJson=async(path)=>JSON.parse(await readFile(resolve(root,path),"utf8"));const [model,browserResults,memoryResults,realTaskStatus]=await Promise.all([readJson("config/maturity-model.json"),readJson("benchmarks/provider-evaluations/browser-results.json"),readJson("benchmarks/provider-evaluations/memory-results.json"),readJson("benchmarks/real-tasks/collection-status-2026-09-29.json")]);return{model,browserResults,memoryResults,realTaskStatus};}
